# Site settings
title: The Best Bits
email: support@thebestbits.co
description: > # this means to ignore newlines until "baseurl:"
  Using only the highest quality 1s and 0s
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thebestbits.co" # the base hostname & protocol for your site
twitter_username: TheBestBitsLLC
github_username:  thebestbits

# Build settings
markdown: kramdown
